### ISSUE TITLE
Link does not allow us to download in our company the JSON Report Plugin

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge-contrib/json-report#6]
All,

We are unable to download the JSON Report Plugin as our security suspects that its a dangerous link : https://github.com/**apoorvam**/json-report/releases/download/0.2.2/json-report-0.2.2-windows.x86_64.zip.

I am able to download the XML Report as it does not have the persons name. Can you please have the repo link corrected for the latest version of JSON Report, so that its inline with the standards for others reports and the security team in my company can download this Report plugin for me.

Thanks,
Hari

**Comment by apoorvam** [comment]
@harimadusumilli It's under a different user account because its a community plugin. I can move this to community profile, https://github.com/getgauge-contrib for further releases. Will that pass the security check?
Is the check based on if it's an organization name or user name? 
Optionally, you can install from source too. If you prefer that, here are [steps](https://github.com/apoorvam/json-report#build-from-source).

**Comment by harimadusumilli** [comment]
Can you please move it to the link you specified. We will try and download
it from there.

Thanks,
Hari

**Comment by apoorvam** [comment]
@harimadusumilli Let me know on what basis the URLs are whitelisted/blacklisted in your use-case? 
Moving the repository to different Github profile needs changes in all releases and links, which takes time. 
I suggest you cache the zip file at your end and install using it, without downloading it every time.

**Comment by sriv** [comment]
@apoorvam I believe transferring repository does not break links, since github says it will redirect all links - https://help.github.com/en/articles/transferring-a-repository#whats-transferred-with-a-repository (see last point in this section)

Do you think this is worth doing along with the impending release?

**Comment by apoorvam** [comment]
@harimadusumilli json-report plugin is now moved getgauge-contrib org and now it should not be a problem for you to download from github. Closing this issue for now.
